site_name: FLIMari Docs
nav:
  - Home: index.md
  - User Guide:
    - User Guide: user-guide/index.md
    - Tutorials: user-guide/tutorials.md
    - Programming Interface: user-guide/api.md
    - Additonal Resources: user-guide/extra.md
  - About: about.md
